services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: playpass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
