services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: playpass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"